// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlVsihNAkfkfP79COTCQT6m5puOcnhOiE',
    appId: '1:1039775939329:web:f7db0f69016d2b0fd3b900',
    messagingSenderId: '1039775939329',
    projectId: 'mattlads-6c722',
    authDomain: 'mattlads-6c722.firebaseapp.com',
    storageBucket: 'mattlads-6c722.appspot.com',
    measurementId: 'G-22E4RKQN6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg2qIUgR_lyWVQm-fwdJSsfGi5OPFH45s',
    appId: '1:1039775939329:android:984d27ddbfe2d3d5d3b900',
    messagingSenderId: '1039775939329',
    projectId: 'mattlads-6c722',
    storageBucket: 'mattlads-6c722.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_s7iu-n8-y3kvP_t9HoFqyhws4TN44_g',
    appId: '1:1039775939329:ios:7a1004e0b1bb261fd3b900',
    messagingSenderId: '1039775939329',
    projectId: 'mattlads-6c722',
    storageBucket: 'mattlads-6c722.appspot.com',
    iosBundleId: 'app.assignify.mattlads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_s7iu-n8-y3kvP_t9HoFqyhws4TN44_g',
    appId: '1:1039775939329:ios:7a1004e0b1bb261fd3b900',
    messagingSenderId: '1039775939329',
    projectId: 'mattlads-6c722',
    storageBucket: 'mattlads-6c722.appspot.com',
    iosBundleId: 'app.assignify.mattlads',
  );
}
